name: Deploy to GitHub Pages with Basic Auth

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        
      - name: Setup Basic Auth
        run: |
          echo "${{ secrets.BASIC_AUTH_USER }}:$(openssl passwd -apr1 ${{ secrets.BASIC_AUTH_PASS }})" > .htpasswd
          echo "AuthType Basic
          AuthName \"Restricted Access\"
          AuthUserFile /path/to/.htpasswd
          Require valid-user" > .htaccess
    
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          enable_jekyll: false
